# Generated by Django 5.1.6 on 2025-12-26 15:54

import datetime
import django.db.models.deletion
import django_jalali.db.models
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('debt', 'بدهی'), ('credit', 'بستانکاری')], max_length=10)),
                ('amount', models.IntegerField(verbose_name='مبلغ')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('is_active', models.BooleanField(default=True)),
                ('previous_cheque_status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'balance_sheet',
            },
        ),
        migrations.CreateModel(
            name='CashierCheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('Cheque_numbder', models.IntegerField(blank=True, null=True)),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('maturity_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='زمان سررسید')),
                ('in_cash', models.CharField(blank=True, max_length=255, null=True)),
                ('cheque_status', models.CharField(choices=[('جاری', 'جاری'), ('وصولی', 'وصولی'), ('برگشتنی', 'برگشتنی'), ('عودتی', 'عودتی'), ('امانی', 'امانی')], default='جاری', max_length=255)),
                ('cheque_type', models.CharField(blank=True, choices=[('پرداختنی', 'پرداختنی'), ('دریافتنی', 'دریافتنی')], max_length=255, null=True)),
            ],
            options={
                'db_table': 'cashier_cheque',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', django_jalali.db.models.jDateField(default=datetime.date(2025, 12, 26))),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='AccountsClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.accountsclass')),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
