# Generated by Django 5.1.6 on 2025-06-03 08:35

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CashierCheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('Cheque_numbder', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('maturity_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='زمان سررسید')),
                ('cheque_status', models.CharField(choices=[('جاری', 'Current'), ('وصولی', 'Collection'), ('برگشتنی', 'Bounced'), ('عودتی', 'Return Ch'), ('امانی', 'Escrow')], default='جاری', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('debt', 'بدهی'), ('credit', 'بستانکاری')], max_length=10)),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='مبلغ')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_sheets', to='account_base.accountsclass')),
            ],
        ),
    ]
