# Generated by Django 5.1.6 on 2025-07-24 11:15

import django.db.models.deletion
import django_jalali.db.models
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='account_base.accountsclass')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CashierCheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('Cheque_numbder', models.IntegerField(blank=True, null=True)),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('maturity_date', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='زمان سررسید')),
                ('cheque_status', models.CharField(choices=[('جاری', 'جاری'), ('وصولی', 'وصولی'), ('برگشتنی', 'برگشتنی'), ('عودتی', 'عودتی'), ('امانی', 'امانی')], default='جاری', max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashiercheque', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('debt', 'بدهی'), ('credit', 'بستانکاری')], max_length=10)),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='مبلغ')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_sheets', to='account_base.accountsclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balancesheet', to=settings.AUTH_USER_MODEL)),
                ('cheque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_sheet', to='account_base.cashiercheque')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='account_base.document')),
            ],
        ),
    ]
