# Generated by Django 5.1.6 on 2025-08-02 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashiercheque',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Bank_cheque', to='account_base.accountsclass'),
        ),
    ]
