# Generated by Django 5.1.6 on 2025-08-11 07:47

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_base', '0002_cashiercheque_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancesheet',
            name='date_created',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now),
        ),
    ]
