# Generated by Django 5.1.6 on 2025-08-11 08:35

import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_base', '0003_alter_balancesheet_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='cheque_status',
            field=models.CharField(blank=True, choices=[('جاری', 'جاری'), ('وصولی', 'وصولی'), ('برگشتنی', 'برگشتنی'), ('عودتی', 'عودتی'), ('امانی', 'امانی')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='date_created',
            field=django_jalali.db.models.jDateField(default=datetime.date(2025, 8, 11)),
        ),
    ]
