# Generated by Django 5.1.6 on 2025-08-11 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_base', '0004_balancesheet_cheque_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancesheet',
            old_name='cheque_status',
            new_name='balance_cheque_status',
        ),
    ]
