# Generated by Django 5.1.6 on 2025-08-11 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_base', '0005_rename_cheque_status_balancesheet_balance_cheque_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancesheet',
            old_name='balance_cheque_status',
            new_name='cheque_status',
        ),
    ]
