# Generated by Django 5.1.6 on 2025-07-03 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_base', '0006_alter_cashiercheque_cheque_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancesheet',
            name='cheque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_sheet', to='account_base.cashiercheque'),
        ),
        migrations.AlterField(
            model_name='cashiercheque',
            name='cheque_status',
            field=models.CharField(choices=[('جاری', 'Current'), ('وصولی', 'Collection'), ('برگشتنی', 'Bounced'), ('عودتی', 'Return Ch'), ('امانی', 'Escrow')], default='جاری', max_length=255),
        ),
    ]
