# Generated by Django 5.1.6 on 2025-07-07 17:24

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_base', '0007_alter_balancesheet_cheque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashiercheque',
            name='cheque_status',
            field=models.CharField(choices=[('جاری', 'Current'), ('وصولی', 'Collection'), ('برگشتنی', 'Bounced'), ('عودتی', 'Return Ch'), ('امانی', 'Escrow')], default='جاری', max_length=255),
        ),
        migrations.AlterField(
            model_name='cashiercheque',
            name='created_at',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
    ]
