# Generated by Django 5.1.6 on 2025-07-23 21:13

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_base', '0008_alter_cashiercheque_cheque_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancesheet',
            name='date_created',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cashiercheque',
            name='cheque_status',
            field=models.CharField(choices=[('جاری', 'Current'), ('وصولی', 'Collection'), ('برگشتنی', 'Bounced'), ('عودتی', 'Return Ch'), ('امانی', 'Escrow')], default='جاری', max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_created',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
    ]
