# Generated by Django 5.1.6 on 2025-08-14 09:30

import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_base', '0008_alter_accountsclass_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancesheet',
            name='cheque_status',
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='date_created',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_created',
            field=django_jalali.db.models.jDateField(default=datetime.date(2025, 8, 14)),
        ),
    ]
