# Generated by Django 5.1.6 on 2025-08-16 10:11

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_base', '0009_remove_balancesheet_cheque_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_created',
            field=django_jalali.db.models.jDateField(default=datetime.date(2025, 8, 16)),
        ),
    ]
