# Generated by Django 5.1.6 on 2025-08-19 15:45

import datetime
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_base', '0010_alter_document_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancesheet',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='مبلغ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='date_created',
            field=django_jalali.db.models.jDateField(default=datetime.date(2025, 8, 19)),
        ),
    ]
