# Generated by Django 5.1.6 on 2025-08-20 12:59

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_base', '0011_alter_balancesheet_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_created',
            field=django_jalali.db.models.jDateField(default=datetime.date(2025, 8, 20)),
        ),
    ]
